### PR TITLE
new stable release v13.0.0

### PR DESCRIPTION
**Pull request by gnapse**
Now that Reactist is back to having all the new changes in a stable non-beta release (v25.0.0), this pull request brings that Reactist version to the ui-extensions, and brings this repo's recent changes in `next` back to `main`.

This pull request will be released as a new version v13.0.0 of the ui extensions react package.

### CODE REVIEW

**Review by scottlovegrove — APPROVED** [review]

**Comment by gnapse** [comment]
Now, after having made the peer dependency change, there's a failed check in CI. Though, it does not look related to the peer dependency change. It's an npm audit warning about the package `braces`. 😕

**Review by scottlovegrove — APPROVED** [review]

**Comment by gnapse** [comment]
@scottlovegrove what's the procedure to release? I assume that after merging I need to do something else, but I'm not sure. I also did not find anything in the README about it.

**Comment by scottlovegrove** [comment]
> @scottlovegrove what's the procedure to release? I assume that after merging I need to do something else, but I'm not sure. I also did not find anything in the README about it.

It just needs a new tag creating once the PR is merged to main. Tag should be `react-v<number>`

I should add that to the readme 👍🏻

**Comment by gnapse** [comment]
I assume the by "a new tag" you mean "a new release" in https://github.com/Doist/ui-extensions/releases, which creates a new tag, and also has a description, etc. I'll create it.

**Pull request merged**
